import re

file_path = 'nongchang/index.html'

with open(file_path, 'r') as f:
    html = f.read()

# 1. Add Tab Button
tab_button = '<button class="tab-btn" data-tab="factory">加工</button>'
if 'data-tab="factory"' not in html:
    html = html.replace('<button class="tab-btn" data-tab="pet">宠物</button>', '<button class="tab-btn" data-tab="pet">宠物</button>\n                ' + tab_button)

# 2. Add Tab Content
factory_content = """
                <!-- Factory Tab -->
                <div id="factory-tab" class="tab-pane">
                    <div class="storage-header">
                        <h3>👨‍🍳 加工坊</h3>
                        <p style="font-size:0.75rem; color:#aaa;">使用基础农作物制作高价值商品</p>
                    </div>

                    <div id="factory-queue" style="padding:10px; background:#222; margin-bottom:10px; border-radius:6px; min-height:60px;">
                        <!-- Active tasks here -->
                        <div style="text-align:center; color:#666; font-size:0.8rem; line-height:40px;">暂无加工任务</div>
                    </div>

                    <div id="recipe-list" class="shop-list" style="flex-grow:1; overflow-y:auto; padding:0 10px;">
                        <!-- Recipes generated by JS -->
                    </div>
                </div>
"""

if 'id="factory-tab"' not in html:
    html = html.replace('<!-- Pet Tab -->', factory_content + '\n\n                <!-- Pet Tab -->')

with open(file_path, 'w') as f:
    f.write(html)

print("Factory UI HTML added.")
